// Generated by CoffeeScript 1.6.3
(function() {
  var dbf_file_name, debug, dps, e, fn, json_file_name1, json_file_name2, p;

  dps = require('../lib/dbf_parser_sync');

  fn = 'employees';

  dbf_file_name = "" + __dirname + "/" + fn + ".dbf";

  json_file_name1 = "" + __dirname + "/" + fn + "1.json";

  json_file_name2 = "" + __dirname + "/" + fn + "2.json";

  debug = true;

  dps.makeJson(dbf_file_name, json_file_name1, debug);

  try {
    p = new dps.DbfParserSync(dbf_file_name);
  } catch (_error) {
    e = _error;
    console.log("Error parsing: " + dbf_file_name);
    throw e;
  }

  p.write_json(json_file_name2);

}).call(this);
