// Generated by CoffeeScript 1.6.3
(function() {
  var DbfParserSync, fn, fs, makeJson, path_from, path_to;

  fs = require('fs');

  DbfParserSync = require('../lib/dbf_parser_sync').DbfParserSync;

  makeJson = function(path_from, path_to) {
    var e, p;
    console.log("----------------------------");
    console.log("Parsing dbf file in: " + path_from);
    console.log("Saving in json file: " + path_to);
    try {
      p = new DbfParserSync(path_from);
    } catch (_error) {
      e = _error;
      console.log("Error parsing: " + path_from);
      console.log(e);
      return null;
    }
    try {
      fs.writeFileSync(path_to, JSON.stringify(p.get_json(), void 0, 2));
    } catch (_error) {
      e = _error;
      console.log("Error writing: " + path_to);
      console.log(e);
      return null;
    }
    console.log("Finished write to %s", path_to);
    return null;
  };

  fn = 'employees';

  path_from = "" + fn + ".dbf";

  path_to = "" + fn + ".json";

  makeJson(path_from, path_to);

}).call(this);
